version: '3'

services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: django-blog-template-web
  #   restart: always
  #   command: ["gunicorn", "blog_project.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "4", "--reload"]
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db

  db:
    image: postgres:12
    container_name: django-blog-template-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
